version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0
  # queue: eddiewebb/queue@2.2.1
  slack: circleci/slack@4.12.5

commands:
  npm-install:
    steps:
      - run:
          name: 'NPM Install'
          command: |
            echo "npm instal..."
  npm-run-build:
    steps:
      - run:
          name: 'npm run build'
          command: |
            echo "npm build..."

jobs:
  Build:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - npm-install
      - npm-run-build

  Auto-merge Dependabot PR:
    parameters:
      patch:
        type: boolean
        default: true
      minor:
        type: boolean
        default: false
      major:
        type: boolean
        default: false
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/setup # Set up GitHub CLI
      - run:
          name: Check merge status
          command: bash .circleci/check-merge-status.sh << parameters.patch >> << parameters.minor >> << parameters.major >>
      - run:
          name: Merge PR
          command: |
            gh pr merge --admin --delete-branch --rebase

workflows:
  version: 2
  My workflow:
    jobs:
      - Build:
          context:
            - NPM_REGISTRY
      - Auto-merge Dependabot PR:
          requires:
            - Build
          patch: true
          minor: true
          major: false
          context:
            - GITHUB_ACCESS
          filters:
            branches:
              only: 
                - /^dependabot.*/
