version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0
  # queue: eddiewebb/queue@2.2.1
  slack: circleci/slack@4.12.5

commands:
  npm-install:
    steps:
      - run:
          name: 'NPM Install'
          command: |
            echo "email=${REGISTRY_EMAIL}" > ~/.npmrc
            echo "always-auth=true" >> ~/.npmrc
            echo "@<SCOPE>:registry=${REGISTRY_URL}" >> ~/.npmrc
            echo "//lpg.jfrog.io/artifactory/api/npm/virt-lpg-npm/:_password=${REGISTRY_PASSWORD}" >> ~/.npmrc
            echo "//lpg.jfrog.io/artifactory/api/npm/virt-lpg-npm/:username=${REGISTRY_EMAIL}" >> ~/.npmrc
            echo "//registry.npmjs.org/:username=${REGISTRY_EMAIL}" >> ~/.npmrc
            echo "//registry.npmjs.org/:_password=${REGISTRY_PASSWORD}" >> ~/.npmrc
            echo "registry=${REGISTRY_URL}" >> ~/.npmrc
            cat ~/.npmrc
            npm i -d 
  npm-run-build:
    steps:
      - run:
          name: 'npm run build'
          command: |
            npm run build

jobs:
  Build:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - npm-install
      - npm-run-build

  Auto-merge Dependabot PR:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # - queue/until_front_of_line:
          # only-on-branch: dependabot*
          # time: '10'
      - gh/setup # Set up GitHub CLI
      - run:
          name: Check merge status
          command: bash .circleci/check-merge-status.sh
      - run:
          # we probably still want to fail in the case of Dependabot trying to bump a dependency to a major version, 
          # even though the build, unit test and e2e tests may be passing (unlikely)
          name: Check for major bumps in package.json
          command: bash .circleci/check-major-bumps.sh
      - slack/notify:
          channel: Stayko
          event: pass
          custom: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":robot_face: Dependabot merged a new PR to main: PR title"
            			},
            			"accessory": {
            				"type": "button",
            				"text": {
            					"type": "plain_text",
            					"text": "View"
            				},
            				"url": "https://github.com/leisurepassgroup/{$CIRCLE_PR_REPONAME}/pull/${CIRCLE_PR_NUMBER}"
            			}
            		}
            	]
            }
      - run:
          name: Merge PR
          command: |
            gh pr merge --admin --delete-branch --rebase

workflows:
  version: 2
  My workflow:
    jobs:
      - Build:
          context:
            - NPM_REGISTRY
      - Auto-merge Dependabot PR:
          requires:
            - Build
          context:
            - GITHUB_ACCESS
            - SLACK
          filters:
            branches:
              only: 
                - /^dependabot.*/
    # triggers:
      # - schedule:
          # cron: "0 9 * * 1-5"
          # filters:
            # branches:
              # only:
                # - /^dependabot.*/
