version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0
  # queue: eddiewebb/queue@2.2.1
  slack: circleci/slack@4.12.5

commands:
  npm-install:
    steps:
      - run:
          name: 'NPM Install'
          command: |
            echo "npm instal..."
  npm-run-build:
    steps:
      - run:
          name: 'npm run build'
          command: |
            echo "npm build..."

jobs:
  Build:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - npm-install
      - npm-run-build

  Auto-merge Dependabot PR:
    parameters:
      patch:
        type: boolean
        default: true
      minor:
        type: boolean
        default: false
      major:
        type: boolean
        default: false
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # - queue/until_front_of_line:
          # only-on-branch: dependabot*
          # time: '10'
      - gh/setup # Set up GitHub CLI
      - run:
          name: Check merge status
          command: bash .circleci/check-merge-status.sh << parameters.patch >> << parameters.minor >> << parameters.major >>
      # - run:
          # we probably still want to fail in the case of Dependabot trying to bump a dependency to a major version, 
          # even though the build, unit test and e2e tests may be passing (unlikely)
          # name: Check for major bumps in package.json
          # command: bash .circleci/check-major-bumps.sh
      # - slack/notify:
          # channel: Stayko
          # event: pass
          # custom: |
            # {
              # "blocks": [
                # {
                  # "type": "section",
                  # "text": {
                    # "type": "mrkdwn",
                    # "text": ":robot_face: Dependabot merged a new PR to main: PR title"
                  # },
                  # "accessory": {
                    # "type": "button",
                    # "text": {
                      # "type": "plain_text",
                      # "text": "View"
                    # },
                    # "url": "https://github.com/leisurepassgroup/{$CIRCLE_PR_REPONAME}/pull/${CIRCLE_PR_NUMBER}"
                  # }
                # }
              # ]
            # }
      - run:
          name: Merge PR
          command: |
            gh pr merge --admin --delete-branch --rebase

workflows:
  version: 2
  My workflow:
    jobs:
      - Build:
          context:
            - NPM_REGISTRY
      - Auto-merge Dependabot PR:
          requires:
            - Build
          parameters:
            patch: true
            minor: true
            major: false
          context:
            - GITHUB_ACCESS
            - SLACK
          filters:
            branches:
              only: 
                - /^dependabot.*/
    # triggers:
      # - schedule:
          # cron: "0 9 * * 1-5"
          # filters:
            # branches:
              # only:
                # - /^dependabot.*/
