version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0
  queue: eddiewebb/queue@2.2.1

commands:
  npm-install:
    steps:
      - run:
          name: 'NPM Install'
          command: 'npm i -d' #https://jfrog.com/help/r/artifactory-how-to-troubleshoot-long-npm-install-times-with-s3-redirect-enabled/workarounds
  npm-run-build:
    steps:
      - run:
          name: 'npm run build'
          command: |
            npm run build

jobs:
  Build:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - npm-install
      - npm-run-build

  Auto-merge Dependabot PR:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - queue/until_front_of_line:
          only-on-branch: /^dependabot.*/
          time: '10'
      - gh/setup # Set up GitHub CLI
      - run:
          name: Check PR Mergeable and MergeStateStatus
          command: |
            mergeable_status=$(gh pr view --json mergeable | jq -r '.mergeable')
            merge_state_status=$(gh pr view --json mergeStateStatus | jq -r '.mergeStateStatus')
            if [ "$mergeable_status" != "MERGEABLE" ] || [ "$merge_state_status" = "BEHIND" ]; then
              echo "PR has conflicts or is out of date with the base branch! Aborting job."
              if [ "$merge_state_status" = "BEHIND" ]; then
                echo "Rebasing the PR branch with the base branch."
                git rebase main
                git push -f
              fi
              circleci step halt
            fi
          when: on_fail
      - run:
          name: Merge PR
          command: |
            gh pr merge --admin --delete-branch --rebase


workflows:
  version: 2
  My workflow:
    jobs:
      - Build
      - Auto-merge Dependabot PR:
          requires:
            - Build
          context:
            - GITHUB_ACCESS
          filters:
            branches:
              only: 
                - /^dependabot.*/
    # triggers:
      # - schedule:
          # cron: "0 9 * * 1-5"
          # filters:
            # branches:
              # only:
                # - /^dependabot.*/
